# Generated by Django 2.0.4 on 2018-05-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='orientation',
            field=models.CharField(choices=[('Vertical', 'Vertical'), ('Horizontal', 'Horizontal')], help_text='Ingrese la Orientación según coordenadas (Ejemplo: Vertical)', max_length=20),
        ),
        migrations.AlterField(
            model_name='camera',
            name='url',
            field=models.URLField(help_text='URL de Acceso', max_length=100),
        ),
    ]
